---
---
---

```{r Echo=FALSE}

library(tidyverse)
library(randomForest)
library(caret)


source("code/data_loading.R")
source("code/title_finders.R")
source("code/column_mutations.R")

# loading and merging data
purchases <- read_csv("C:\\Users\\tessa\\OneDrive\\Desktop\\Masters 2023\\Data science\\Project\\data\\Full_Rec_Mooc_Purchases.csv") %>% select(mooc_id, buyer_id)
auctions <- read_csv("C:\\Users\\tessa\\OneDrive\\Desktop\\Masters 2023\\Data science\\Project\\data\\Full_Rec_Mooc.csv") %>% select(mooc_id, date, auction_tot)
final_df <- data_loader("C:\\Users\\tessa\\OneDrive\\Desktop\\Masters 2023\\Data science\\Project\\data")
merged_df <- merger(final_df)


# counting total number of good types per auction 
merged_df <- merged_df %>% group_by(mooc_id) %>% mutate(number_bundles=sum(bundle))%>% separate(date, into =c('year', 'month/day'), sep=4)
merged_df <- good_counter(merged_df, c("books", "art_products", "scales", "beds", "cattle", "chairs", "china", "coatrack", "cups", "guns", "hammers", "horse_cart", "horses", "irons", "jewelry", "lamps", "oven", "plates", "pot", "sheep", "slaves", "tables", "utensils", "wagons"), c("book_tot", "art_tot", "scale_tot", "bed_tot", "cattle_tot", "chairs_tot", "china_tot", "coatrack_tot", "cup_tot", "guns_tot", "hammer_tot", "horsecart_tot", "horse_tot", "irons_tot", "jewelry_tot", "lamp_tot", "oven_tot", "plates_tot", "pot_total", "sheep_tot", "slave_tot", "table_tot", "utensil_tot", "wagon_tot" )) 
merged_df <- merged_df %>% distinct(mooc_id, .keep_all=TRUE)

# counting attendance by titled men and women per auction
women <- titledwomen_locator(titled_women, purchases$buyer_id)
men <- titledmen_locator(titled_men, purchases$buyer_id)
purchases_df <- tibble(purchases, women, men)
purchases_df <- purchases_df %>% group_by(mooc_id) %>% 
    mutate(women_tot=sum(women, na.rm=TRUE)) %>% mutate(men_total=sum(men, na.rm=TRUE)) %>% 
    select(mooc_id, women_tot, men_total) %>% 
    distinct(mooc_id, .keep_all=TRUE)
### title_counter("women_tot", "women")

# merging titles and auctions
merged_df <- inner_join(merged_df,purchases_df, by="mooc_id") %>% select(-`month/day`, type)
merged_df <- merged_df %>%  
    arrange(year) %>% 
    group_by(year) %>% 
    mutate(date=n())
merged_df$date <- as.numeric(match(merged_df$year, unique(merged_df$year)))
merged_df <- merged_df %>% filter(date<103) %>% filter(date!=1) %>% na.omit() 
merged_df$auction_tot <- as.numeric(merged_df$auction_tot)
plotting_df <- merged_df %>% 
        filter(auction_tot>60) %>% arrange(year)
merged_df <- merged_df %>% ungroup() %>% select(-mooc_id,-year, -type, -bundle) %>% 
    filter(auction_tot>60)

```

```{r Echo=FALSE}

source("code/ggplots.R")

auction_timeline <- plotter(plotting_df, plotting_df$year, plotting_df$auction_tot)
auction_timeline

attendance_plot <- ggplot(attendance_df, aes(x=year, y=number, fill=title))+
        geom_bar(stat="identity")+
        labs(title="Attendance by titled men and women per auction", 
             x="Date", y="Number of titled attendees")+
        theme(plot.title = element_text(hjust = 0.5, vjust=2))+
        theme(axis.title.y = element_text(margin = margin(r = 10)))+
        theme(axis.title.y = element_text(hjust = 0.5))+
        theme(axis.title.x = element_text(margin = margin(t = 10)))+
        theme(axis.title.x = element_text(hjust = 0.5))+
        theme(plot.margin = margin(15, 10, 15, 10))+
        theme(axis.text.x = element_text(angle = 45, hjust = 1))
attendance_plot

slave_purchases <- plotter(plotting_df$slave_tot,"Total number of slaves sold per auction", "Number")
slave_purchases

wagon_purchases <- plotter(plotting_df$wagon_tot,"Total number of wagons sold per auction", "Number")
wagon_purchases

horse_purchases <- plotter(plotting_df$horse_tot,"Total number of horses sold per auction", "Number")
horse_purchases


```
